name: storage
description: 'A new Flutter plugin project.'
version: 0.0.1
homepage: https://github.com/yanshouwang/storage
issue_tracker: https://github.com/yanshouwang/storage/issues
topics:
  - storage

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^24.2.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.hebei.storage
        pluginClass: StoragePlugin
