// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.hebei.storage

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is StorageError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): StorageError {
  return StorageError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class StorageError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/**
 * Maintains instances used to communicate with the corresponding objects in Dart.
 *
 * Objects stored in this container are represented by an object in Dart that is also stored in
 * an InstanceManager with the same identifier.
 *
 * When an instance is added with an identifier, either can be used to retrieve the other.
 *
 * Added instances are added as a weak reference and a strong reference. When the strong
 * reference is removed with [remove] and the weak reference is deallocated, the
 * `finalizationListener.onFinalize` is called with the instance's identifier. However, if the strong
 * reference is removed and then the identifier is retrieved with the intention to pass the identifier
 * to Dart (e.g. calling [getIdentifierForStrongReference]), the strong reference to the instance
 * is recreated. The strong reference will then need to be removed manually again.
 */
@Suppress("UNCHECKED_CAST", "MemberVisibilityCanBePrivate")
class StoragePigeonInstanceManager(private val finalizationListener: PigeonFinalizationListener) {
  /** Interface for listening when a weak reference of an instance is removed from the manager.  */
  interface PigeonFinalizationListener {
    fun onFinalize(identifier: Long)
  }

  private val identifiers = java.util.WeakHashMap<Any, Long>()
  private val weakInstances = HashMap<Long, java.lang.ref.WeakReference<Any>>()
  private val strongInstances = HashMap<Long, Any>()
  private val referenceQueue = java.lang.ref.ReferenceQueue<Any>()
  private val weakReferencesToIdentifiers = HashMap<java.lang.ref.WeakReference<Any>, Long>()
  private val handler = android.os.Handler(android.os.Looper.getMainLooper())
  private var nextIdentifier: Long = minHostCreatedIdentifier
  private var hasFinalizationListenerStopped = false

  /**
   * Modifies the time interval used to define how often this instance removes garbage collected
   * weak references to native Android objects that this instance was managing.
   */
  var clearFinalizedWeakReferencesInterval: Long = 3000
    set(value) {
      handler.removeCallbacks { this.releaseAllFinalizedInstances() }
      field = value
      releaseAllFinalizedInstances()
    }

  init {
    handler.postDelayed(
      { releaseAllFinalizedInstances() },
      clearFinalizedWeakReferencesInterval
    )
  }

  companion object {
    // Identifiers are locked to a specific range to avoid collisions with objects
    // created simultaneously from Dart.
    // Host uses identifiers >= 2^16 and Dart is expected to use values n where,
    // 0 <= n < 2^16.
    private const val minHostCreatedIdentifier: Long = 65536
    private const val tag = "PigeonInstanceManager"

    /**
     * Instantiate a new manager with a listener for garbage collected weak
     * references.
     *
     * When the manager is no longer needed, [stopFinalizationListener] must be called.
     */
    fun create(finalizationListener: PigeonFinalizationListener): StoragePigeonInstanceManager {
      return StoragePigeonInstanceManager(finalizationListener)
    }
  }

  /**
   * Removes `identifier` and return its associated strongly referenced instance, if present,
   * from the manager.
   */
  fun <T> remove(identifier: Long): T? {
    logWarningIfFinalizationListenerHasStopped()
    return strongInstances.remove(identifier) as T?
  }

  /**
   * Retrieves the identifier paired with an instance, if present, otherwise `null`.
   *
   *
   * If the manager contains a strong reference to `instance`, it will return the identifier
   * associated with `instance`. If the manager contains only a weak reference to `instance`, a new
   * strong reference to `instance` will be added and will need to be removed again with [remove].
   *
   *
   * If this method returns a nonnull identifier, this method also expects the Dart
   * `StoragePigeonInstanceManager` to have, or recreate, a weak reference to the Dart instance the
   * identifier is associated with.
   */
  fun getIdentifierForStrongReference(instance: Any?): Long? {
    logWarningIfFinalizationListenerHasStopped()
    val identifier = identifiers[instance]
    if (identifier != null) {
      strongInstances[identifier] = instance!!
    }
    return identifier
  }

  /**
   * Adds a new instance that was instantiated from Dart.
   *
   * The same instance can be added multiple times, but each identifier must be unique. This
   * allows two objects that are equivalent (e.g. the `equals` method returns true and their
   * hashcodes are equal) to both be added.
   *
   * [identifier] must be >= 0 and unique.
   */
  fun addDartCreatedInstance(instance: Any, identifier: Long) {
    logWarningIfFinalizationListenerHasStopped()
    addInstance(instance, identifier)
  }

  /**
   * Adds a new unique instance that was instantiated from the host platform.
   *
   * [identifier] must be >= 0 and unique.
   */
  fun addHostCreatedInstance(instance: Any): Long {
    logWarningIfFinalizationListenerHasStopped()
    require(!containsInstance(instance)) { "Instance of ${instance.javaClass} has already been added." }
    val identifier = nextIdentifier++
    addInstance(instance, identifier)
    return identifier
  }

  /** Retrieves the instance associated with identifier, if present, otherwise `null`. */
  fun <T> getInstance(identifier: Long): T? {
    logWarningIfFinalizationListenerHasStopped()
    val instance = weakInstances[identifier] as java.lang.ref.WeakReference<T>?
    return instance?.get()
  }

  /** Returns whether this manager contains the given `instance`. */
  fun containsInstance(instance: Any?): Boolean {
    logWarningIfFinalizationListenerHasStopped()
    return identifiers.containsKey(instance)
  }

  /**
   * Stops the periodic run of the [PigeonFinalizationListener] for instances that have been garbage
   * collected.
   *
   * The InstanceManager can continue to be used, but the [PigeonFinalizationListener] will no
   * longer be called and methods will log a warning.
   */
  fun stopFinalizationListener() {
    handler.removeCallbacks { this.releaseAllFinalizedInstances() }
    hasFinalizationListenerStopped = true
  }

  /**
   * Removes all of the instances from this manager.
   *
   * The manager will be empty after this call returns.
   */
  fun clear() {
    identifiers.clear()
    weakInstances.clear()
    strongInstances.clear()
    weakReferencesToIdentifiers.clear()
  }

  /**
   * Whether the [PigeonFinalizationListener] is still being called for instances that are garbage
   * collected.
   *
   * See [stopFinalizationListener].
   */
  fun hasFinalizationListenerStopped(): Boolean {
    return hasFinalizationListenerStopped
  }

  private fun releaseAllFinalizedInstances() {
    if (hasFinalizationListenerStopped()) {
      return
    }
    var reference: java.lang.ref.WeakReference<Any>?
    while ((referenceQueue.poll() as java.lang.ref.WeakReference<Any>?).also { reference = it } != null) {
      val identifier = weakReferencesToIdentifiers.remove(reference)
      if (identifier != null) {
        weakInstances.remove(identifier)
        strongInstances.remove(identifier)
        finalizationListener.onFinalize(identifier)
      }
    }
    handler.postDelayed(
      { releaseAllFinalizedInstances() },
      clearFinalizedWeakReferencesInterval
    )
  }

  private fun addInstance(instance: Any, identifier: Long) {
    require(identifier >= 0) { "Identifier must be >= 0: $identifier" }
    require(!weakInstances.containsKey(identifier)) {
      "Identifier has already been added: $identifier"
    }
    val weakReference = java.lang.ref.WeakReference(instance, referenceQueue)
    identifiers[instance] = identifier
    weakInstances[identifier] = weakReference
    weakReferencesToIdentifiers[weakReference] = identifier
    strongInstances[identifier] = instance
  }

  private fun logWarningIfFinalizationListenerHasStopped() {
    if (hasFinalizationListenerStopped()) {
      Log.w(
        tag,
        "The manager was used after calls to the PigeonFinalizationListener has been stopped."
      )
    }
  }
}


/** Generated API for managing the Dart and native `InstanceManager`s. */
private class StoragePigeonInstanceManagerApi(val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by StoragePigeonInstanceManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      StoragePigeonCodec()
    }

    /**
     * Sets up an instance of `StoragePigeonInstanceManagerApi` to handle messages from the
     * `binaryMessenger`.
     */
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, instanceManager: StoragePigeonInstanceManager?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.PigeonInternalInstanceManager.removeStrongReference", codec)
        if (instanceManager != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              instanceManager.remove<Any?>(identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.PigeonInternalInstanceManager.clear", codec)
        if (instanceManager != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              instanceManager.clear()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  fun removeStrongReference(identifierArg: Long, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.storage.PigeonInternalInstanceManager.removeStrongReference"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(identifierArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Provides implementations for each ProxyApi implementation and provides access to resources
 * needed by any implementation.
 */
abstract class StoragePigeonProxyApiRegistrar(val binaryMessenger: BinaryMessenger) {
  /** Whether APIs should ignore calling to Dart. */
  public var ignoreCallsToDart = false
  val instanceManager: StoragePigeonInstanceManager
  private var _codec: MessageCodec<Any?>? = null
  val codec: MessageCodec<Any?>
    get() {
      if (_codec == null) {
        _codec = StoragePigeonProxyApiBaseCodec(this)
      }
      return _codec!!
    }

  init {
    val api = StoragePigeonInstanceManagerApi(binaryMessenger)
    instanceManager = StoragePigeonInstanceManager.create(
      object : StoragePigeonInstanceManager.PigeonFinalizationListener {
        override fun onFinalize(identifier: Long) {
          api.removeStrongReference(identifier) {
            if (it.isFailure) {
              Log.e(
                "PigeonProxyApiRegistrar",
                "Failed to remove Dart strong reference with identifier: $identifier"
              )
            }
          }
        }
      }
    )
  }
  /**
   * An implementation of [PigeonApiStoragePlugin] used to add a new Dart instance of
   * `StoragePlugin` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiStoragePlugin(): PigeonApiStoragePlugin

  /**
   * An implementation of [PigeonApiVolume] used to add a new Dart instance of
   * `Volume` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiVolume(): PigeonApiVolume

  /**
   * An implementation of [PigeonApiStorageEventListener] used to add a new Dart instance of
   * `StorageEventListener` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiStorageEventListener(): PigeonApiStorageEventListener

  /**
   * An implementation of [PigeonApiContext] used to add a new Dart instance of
   * `Context` to the Dart `InstanceManager`.
   */
  open fun getPigeonApiContext(): PigeonApiContext
  {
    return PigeonApiContext(this)
  }

  /**
   * An implementation of [PigeonApiContextCompat] used to add a new Dart instance of
   * `ContextCompat` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiContextCompat(): PigeonApiContextCompat

  /**
   * An implementation of [PigeonApiExecutor] used to add a new Dart instance of
   * `Executor` to the Dart `InstanceManager`.
   */
  open fun getPigeonApiExecutor(): PigeonApiExecutor
  {
    return PigeonApiExecutor(this)
  }

  /**
   * An implementation of [PigeonApiStorageManager] used to add a new Dart instance of
   * `StorageManager` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiStorageManager(): PigeonApiStorageManager

  fun setUp() {
    StoragePigeonInstanceManagerApi.setUpMessageHandlers(binaryMessenger, instanceManager)
    PigeonApiStoragePlugin.setUpMessageHandlers(binaryMessenger, getPigeonApiStoragePlugin())
    PigeonApiVolume.setUpMessageHandlers(binaryMessenger, getPigeonApiVolume())
    PigeonApiStorageEventListener.setUpMessageHandlers(binaryMessenger, getPigeonApiStorageEventListener())
    PigeonApiContextCompat.setUpMessageHandlers(binaryMessenger, getPigeonApiContextCompat())
    PigeonApiStorageManager.setUpMessageHandlers(binaryMessenger, getPigeonApiStorageManager())
  }
  fun tearDown() {
    StoragePigeonInstanceManagerApi.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiStoragePlugin.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiVolume.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiStorageEventListener.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiContextCompat.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiStorageManager.setUpMessageHandlers(binaryMessenger, null)
  }
}
private class StoragePigeonProxyApiBaseCodec(val registrar: StoragePigeonProxyApiRegistrar) : StoragePigeonCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        val identifier: Long = readValue(buffer) as Long
        val instance: Any? = registrar.instanceManager.getInstance(identifier)
        if (instance == null) {
          Log.e(
            "PigeonProxyApiBaseCodec",
            "Failed to find instance with identifier: $identifier"
          )
        }
        return instance
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    if (value is Boolean || value is ByteArray || value is Double || value is DoubleArray || value is FloatArray || value is Int || value is IntArray || value is List<*> || value is Long || value is LongArray || value is Map<*, *> || value is String || value is VolumeState || value == null) {
      super.writeValue(stream, value)
      return
    }

    if (value is dev.hebei.storage.StoragePlugin) {
      registrar.getPigeonApiStoragePlugin().pigeon_newInstance(value) { }
    }
     else if (value is dev.hebei.storage.Volume) {
      registrar.getPigeonApiVolume().pigeon_newInstance(value) { }
    }
     else if (value is dev.hebei.storage.StorageEventListener) {
      registrar.getPigeonApiStorageEventListener().pigeon_newInstance(value) { }
    }
     else if (value is android.content.Context) {
      registrar.getPigeonApiContext().pigeon_newInstance(value) { }
    }
     else if (value is androidx.core.content.ContextCompat) {
      registrar.getPigeonApiContextCompat().pigeon_newInstance(value) { }
    }
     else if (value is java.util.concurrent.Executor) {
      registrar.getPigeonApiExecutor().pigeon_newInstance(value) { }
    }
     else if (value is android.os.storage.StorageManager) {
      registrar.getPigeonApiStorageManager().pigeon_newInstance(value) { }
    }

    when {
      registrar.instanceManager.containsInstance(value) -> {
        stream.write(128)
        writeValue(stream, registrar.instanceManager.getIdentifierForStrongReference(value))
      }
      else -> throw IllegalArgumentException("Unsupported value: '$value' of type '${value.javaClass.name}'")
    }
  }
}

enum class VolumeState(val raw: Int) {
  UNKNOWN(0),
  UNMOUNTED(1),
  CHECKING(2),
  MOUNTED(3),
  MOUNTED_READ_ONLY(4),
  FORMATTING(5),
  EJECTING(6),
  UNMOUNTABLE(7),
  REMOVED(8),
  BAD_REMOVAL(9);

  companion object {
    fun ofRaw(raw: Int): VolumeState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class StoragePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VolumeState.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VolumeState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}

@Suppress("UNCHECKED_CAST")
abstract class PigeonApiStoragePlugin(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  abstract fun instance(): dev.hebei.storage.StoragePlugin

  abstract fun context(pigeon_instance: dev.hebei.storage.StoragePlugin): android.content.Context

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiStoragePlugin?) {
      val codec = api?.pigeonRegistrar?.codec ?: StoragePigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.StoragePlugin.instance", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.instance(), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.StoragePlugin.context", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.StoragePlugin
            val pigeon_identifierArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.context(pigeon_instanceArg), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of StoragePlugin and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: dev.hebei.storage.StoragePlugin, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.storage.StoragePlugin.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * Information about a shared/external storage volume for a specific user.
 *
 * A device always has one (and one only) primary storage volume, but it could
 * have extra volumes, like SD cards and USB drives. This object represents the
 * logical view of a storage volume for a specific user: different users might
 * have different views for the same physical volume (for example, if the volume
 * is a built-in emulated storage).
 *
 * The storage volume is not necessarily mounted, applications should use getState()
 * to verify its state.
 *
 * Applications willing to read or write to this storage volume needs to get a
 * permission from the user first, which can be achieved in the following ways:
 *
 * * To get access to standard directories (like the Environment.DIRECTORY_PICTURES),
 * they can use the createAccessIntent(java.lang.String). This is the recommend
 * way, since it provides a simpler API and narrows the access to the given
 * directory (and its descendants).
 * * To get access to any directory (and its descendants), they can use the
 * Storage Access Framework APIs (such as Intent.ACTION_OPEN_DOCUMENT and
 * Intent.ACTION_OPEN_DOCUMENT_TREE, although these APIs do not guarantee the
 * user will select this specific volume.
 * * To get read and write access to the primary storage volume, applications
 * can declare the android.Manifest.permission#READ_EXTERNAL_STORAGE and
 * android.Manifest.permission#WRITE_EXTERNAL_STORAGE permissions respectively,
 * with the latter including the former. This approach is discouraged, since
 * users may be hesitant to grant broad access to all files contained on a storage
 * device.
 *
 * It can be obtained through StorageManager.getStorageVolumes() and
 * StorageManager.getPrimaryStorageVolume() and also as an extra in some broadcasts
 * (see EXTRA_STORAGE_VOLUME).
 *
 * See Environment.getExternalStorageDirectory() for more info about shared/external
 * storage semantics.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiVolume(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  abstract fun getId(pigeon_instance: dev.hebei.storage.Volume): String

  /**
   * Returns the directory where this volume is currently mounted.
   *
   * Direct filesystem access via this path has significant emulation overhead,
   * and apps are instead strongly encouraged to interact with media on storage
   * volumes via the MediaStore APIs.
   *
   * This directory does not give apps any additional access beyond what they
   * already have via MediaStore.
   */
  abstract fun getPath(pigeon_instance: dev.hebei.storage.Volume): String?

  /** Returns the current state of the volume. */
  abstract fun getState(pigeon_instance: dev.hebei.storage.Volume): VolumeState

  /** Returns true if the volume is emulated. */
  abstract fun isEmulated(pigeon_instance: dev.hebei.storage.Volume): Boolean

  /**
   * Returns true if the volume is the primary shared/external storage, which is
   * the volume backed by Environment.getExternalStorageDirectory().
   */
  abstract fun isPrimary(pigeon_instance: dev.hebei.storage.Volume): Boolean

  /** Returns true if the volume is removable. */
  abstract fun isRemovable(pigeon_instance: dev.hebei.storage.Volume): Boolean

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiVolume?) {
      val codec = api?.pigeonRegistrar?.codec ?: StoragePigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.Volume.getId", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.Volume
            val wrapped: List<Any?> = try {
              listOf(api.getId(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.Volume.getPath", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.Volume
            val wrapped: List<Any?> = try {
              listOf(api.getPath(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.Volume.getState", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.Volume
            val wrapped: List<Any?> = try {
              listOf(api.getState(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.Volume.isEmulated", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.Volume
            val wrapped: List<Any?> = try {
              listOf(api.isEmulated(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.Volume.isPrimary", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.Volume
            val wrapped: List<Any?> = try {
              listOf(api.isPrimary(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.Volume.isRemovable", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.storage.Volume
            val wrapped: List<Any?> = try {
              listOf(api.isRemovable(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Volume and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: dev.hebei.storage.Volume, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.storage.Volume.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiStorageEventListener(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  abstract fun pigeon_defaultConstructor(): dev.hebei.storage.StorageEventListener

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiStorageEventListener?) {
      val codec = api?.pigeonRegistrar?.codec ?: StoragePigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.StorageEventListener.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of StorageEventListener and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: dev.hebei.storage.StorageEventListener, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      callback(
          Result.failure(
              StorageError("new-instance-error", "Attempting to create a new Dart instance of StorageEventListener, but the class has a nonnull callback method.", "")))
    }
  }

  fun onVolumeStateChanged(pigeon_instanceArg: dev.hebei.storage.StorageEventListener, volumeArg: dev.hebei.storage.Volume, oldStateArg: VolumeState, newStateArg: VolumeState, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
      return
    }
    val binaryMessenger = pigeonRegistrar.binaryMessenger
    val codec = pigeonRegistrar.codec
    val channelName = "dev.flutter.pigeon.storage.StorageEventListener.onVolumeStateChanged"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pigeon_instanceArg, volumeArg, oldStateArg, newStateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }

}
/**
 * Interface to global information about an application environment. This is an
 * abstract class whose implementation is provided by the Android system. It
 * allows access to application-specific resources and classes, as well as up-calls
 * for application-level operations such as launching activities, broadcasting
 * and receiving intents, etc.
 */
@Suppress("UNCHECKED_CAST")
open class PigeonApiContext(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Context and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.content.Context, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.storage.Context.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/** Helper for accessing features in Context. */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiContextCompat(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  /**
   * Return an Executor that will run enqueued tasks on the main thread associated
   * with this context. This is the thread used to dispatch calls to application
   * components (activities, services, etc).
   */
  abstract fun getMainExecutor(context: android.content.Context): java.util.concurrent.Executor

  /** Return the handle to a system-level service by class. */
  abstract fun getStorageManager(context: android.content.Context): android.os.storage.StorageManager?

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiContextCompat?) {
      val codec = api?.pigeonRegistrar?.codec ?: StoragePigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.ContextCompat.getMainExecutor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contextArg = args[0] as android.content.Context
            val wrapped: List<Any?> = try {
              listOf(api.getMainExecutor(contextArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.ContextCompat.getStorageManager", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contextArg = args[0] as android.content.Context
            val wrapped: List<Any?> = try {
              listOf(api.getStorageManager(contextArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of ContextCompat and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: androidx.core.content.ContextCompat, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.storage.ContextCompat.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * An object that executes submitted Runnable tasks. This interface provides a
 * way of decoupling task submission from the mechanics of how each task will be
 * run, including details of thread use, scheduling, etc. An Executor is normally
 * used instead of explicitly creating threads. For example, rather than invoking
 * new Thread(new RunnableTask()).start() for each of a set of tasks, you might
 * use:
 *
 * ``` Kotlin
 * <code>Executor executor = anExecutor();
 *  executor.execute(new RunnableTask1());
 *  executor.execute(new RunnableTask2());
 *  ...</code>
 * ```
 *
 * However, the Executor interface does not strictly require that execution be
 * asynchronous. In the simplest case, an executor can run the submitted task
 * immediately in the caller's thread:
 *
 * ``` Kotlin
 * <code>class DirectExecutor implements Executor {
 *    public void execute(Runnable r) {
 *      r.run();
 *    }
 *  }</code>
 * ```
 *
 * More typically, tasks are executed in some thread other than the caller's
 * thread. The executor below spawns a new thread for each task.
 *
 * ``` Kotlin
 * <code>class ThreadPerTaskExecutor implements Executor {
 *    public void execute(Runnable r) {
 *      new Thread(r).start();
 *    }
 *  }</code>
 * ```
 *
 * Many Executor implementations impose some sort of limitation on how and when
 * tasks are scheduled. The executor below serializes the submission of tasks to
 * a second executor, illustrating a composite executor.
 *
 * ``` Kotlin
 * <code>class SerialExecutor implements Executor {
 *    final Queue&lt;Runnable&gt; tasks = new ArrayDeque&lt;&gt;();
 *    final Executor executor;
 *    Runnable active;
 *
 *    SerialExecutor(Executor executor) {
 *      this.executor = executor;
 *    }
 *
 *    public synchronized void execute(Runnable r) {
 *      tasks.add(() -&gt; {
 *        try {
 *          r.run();
 *        } finally {
 *          scheduleNext();
 *        }
 *      });
 *      if (active == null) {
 *        scheduleNext();
 *      }
 *    }
 *
 *    protected synchronized void scheduleNext() {
 *      if ((active = tasks.poll()) != null) {
 *        executor.execute(active);
 *      }
 *    }
 *  }</code>
 * ```
 *
 * The Executor implementations provided in this package implement ExecutorService,
 * which is a more extensive interface. The ThreadPoolExecutor class provides an
 * extensible thread pool implementation. The Executors class provides convenient
 * factory methods for these Executors.
 *
 * Memory consistency effects: Actions in a thread prior to submitting a Runnable
 * object to an Executor happen-before its execution begins, perhaps in another
 * thread.
 */
@Suppress("UNCHECKED_CAST")
open class PigeonApiExecutor(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Executor and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: java.util.concurrent.Executor, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.storage.Executor.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * StorageManager is the interface to the systems storage service. The storage
 * manager handles storage-related items such as Opaque Binary Blobs (OBBs).
 *
 * OBBs contain a filesystem that maybe be encrypted on disk and mounted on-demand
 * from an application. OBBs are a good way of providing large amounts of binary
 * assets without packaging them into APKs as they may be multiple gigabytes in
 * size. However, due to their size, they're most likely stored in a shared
 * storage pool accessible from all programs. The system does not guarantee the
 * security of the OBB file itself: if any program modifies the OBB, there is no
 * guarantee that a read from that OBB will produce the expected output.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiStorageManager(open val pigeonRegistrar: StoragePigeonProxyApiRegistrar) {
  abstract fun getVolumes(pigeon_instance: android.os.storage.StorageManager): List<dev.hebei.storage.Volume>

  abstract fun registerListener(pigeon_instance: android.os.storage.StorageManager, listener: dev.hebei.storage.StorageEventListener)

  abstract fun unregisterListener(pigeon_instance: android.os.storage.StorageManager, listener: dev.hebei.storage.StorageEventListener)

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiStorageManager?) {
      val codec = api?.pigeonRegistrar?.codec ?: StoragePigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.StorageManager.getVolumes", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.os.storage.StorageManager
            val wrapped: List<Any?> = try {
              listOf(api.getVolumes(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.StorageManager.registerListener", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.os.storage.StorageManager
            val listenerArg = args[1] as dev.hebei.storage.StorageEventListener
            val wrapped: List<Any?> = try {
              api.registerListener(pigeon_instanceArg, listenerArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.storage.StorageManager.unregisterListener", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.os.storage.StorageManager
            val listenerArg = args[1] as dev.hebei.storage.StorageEventListener
            val wrapped: List<Any?> = try {
              api.unregisterListener(pigeon_instanceArg, listenerArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of StorageManager and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.os.storage.StorageManager, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              StorageError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.storage.StorageManager.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(StorageError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
